version: '3.8'
services:
  markets_nexus_api:
    # name: "dev_markets-nexus-api"
    image: "mcr.microsoft.com/devcontainers/dotnet:10.0-noble"
    volumes:
      - ../:/workspaces/markets-nexus-api
    command: sleep infinity
